# Generated by Django 4.1.5 on 2023-01-12 03:14

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='address_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_2',
            field=models.CharField(default='address', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='address', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='customer',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default='address', max_length=200),
        ),
    ]
